name: Test Landing Page on Firefox Browser

on:
  push:
    branches:
      - web-landingPage-test

jobs:
  landingPage-run:
    name: Run Landing Page Tests on Firefox
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Landing Page Test on Firefox
        uses: cypress-io/github-action@v6
        with:
          working-directory: web-automation
          install: true
          browser: firefox
          command: npm run test:landingPage-test
          record: true
        env:
          CYPRESS_RECORD_KEY:  757222a2-1275-4e82-b3f3-bf3bdf69552a
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: landingpage-firefox-report
          path: web-automation/cypress/reports/html

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: landingpage-firefox-videos
          path: web-automation/cypress/videos
