name: Test Landing page on Chrome browser
on:
  push:
    branches:
      - web-landingPage-test

jobs:
  landingPage-run:
    name: Test LandingPage on Chrome browser
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run landing Page Test
        uses: cypress-io/github-action@v6
        with:
          working-directory: web-automation
          # This triggers the 'npm run test:landingPage-test' but adds the --record flag
          command: npm run test:landingPage-test -- --record
          record: true
        env:
          # Use GitHub Secrets for the Record Key (Recommended)
          # Go to Settings > Secrets and variables > Actions > New repository secret
          # Name: CYPRESS_RECORD_KEY, Value: your_key_here
          CYPRESS_RECORD_KEY: 757222a2-1275-4e82-b3f3-bf3bdf69552a
      

      - name: Upload Report
        if: always() # Ensures reports upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: LandingPage-Test-report
          path: web-automation/cypress/reports/html
